return {
  -- {
  --   "nvim-treesitter/nvim-treesitter",
  --   opts = function(_, opts)
  --     opts.highlight = opts.highlight or {}
  --     if type(opts.ensure_installed) == "table" then
  --       vim.list_extend(opts.ensure_installed, { "bibtex" })
  --     end
  --     if type(opts.highlight.disable) == "table" then
  --       vim.list_extend(opts.highlight.disable, { "latex" })
  --     else
  --       opts.highlight.disable = { "latex" }
  --     end
  --   end,
  -- },
  -- {
  --   "neovim/nvim-lspconfig",
  --   optional = true,
  --   opts = {
  --     servers = {
  --       texlab = {
  --         keys = {
  --           { "<Leader>K", "<plug>(vimtex-doc-package)", desc = "Vimtex Docs", silent = true },
  --         },
  --       },
  --     },
  --   },
  -- }
}
